[workspace]
authors = ["Arun <ajoseph.lobo@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mandelbrot"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "<1.0.0"
python = ">=3.13.7,<3.14"
pygame = ">=2.6.1,<3"
